"""Assemble and write the final per-company HTML report."""
from __future__ import annotations

from pathlib import Path
from typing import Dict, Optional
import sys

sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from config import OUTPUT_DIR, INSURANCE_COGS_MIN_PCT, BANK_PROVISION_MAX_PCT
from src.analysis.segment_aggregator import AggregatedCompanyData
from src.visualization.sankey_builder import SankeyData, build_sankey
from src.visualization.sankey_renderer import render_sankey_html

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def generate_report(
    agg:            AggregatedCompanyData,
    analysis_text:  str,
) -> Path:
    """
    Build the full HTML report for a company:
    - Period-dropdown Sankey chart (FY2022/FY2023/FY2024)
    - Business model narrative
    - Segment coverage table
    - Data sources footer

    Returns the path to the written HTML file.
    """
    # Build Sankey data for each annual period
    sankey_by_period: Dict[str, Optional[SankeyData]] = {}
    for sd in agg.annual_periods:
        sankey_by_period[sd.period] = build_sankey(sd, sector=agg.sector)

    # Filter out None periods
    sankey_by_period = {p: s for p, s in sankey_by_period.items() if s is not None}

    # Render the Sankey HTML with period switcher
    sankey_html = render_sankey_html(sankey_by_period, agg.name, agg.ticker)

    # Convert analysis Markdown to HTML
    analysis_html = _markdown_to_html(analysis_text)

    # Build segment coverage table
    coverage_html = _build_coverage_table(agg)

    # Build income statement table
    income_stmt_html = _build_income_statement_table(agg)

    # Build data sources section
    sources_html = _build_sources_section(agg)

    # Partial data warning
    warning_html = ""
    if agg.has_partial_data:
        warning_html = f"""
<div style="background:#fff3cd;border:1px solid #ffc107;padding:10px 16px;
            border-radius:6px;margin:12px 0;font-size:13px;">
  ⚠ <strong>Partial Data:</strong> {" | ".join(agg.data_notes)}
</div>"""

    full_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{agg.name} ({agg.ticker}) — Financial Analysis</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
          max-width: 1600px; margin: 0 auto; padding: 20px; background: #f5f5f5; }}
  .chart-container, #sankey-chart {{ width: 100% !important; }}
  #sankey-chart .plot-container, #sankey-chart .svg-container {{ width: 100% !important; }}
  h2, h3 {{ color: #1a1a2e; }}
  .section {{ background: white; border-radius: 8px; padding: 20px 24px;
              margin-bottom: 16px; box-shadow: 0 1px 4px rgba(0,0,0,0.08); }}
  .section h3 {{ margin-top: 0; border-bottom: 2px solid #1a1a2e; padding-bottom: 8px; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  th {{ background: #1a1a2e; color: white; padding: 8px 12px; text-align: left; }}
  td {{ padding: 7px 12px; border-bottom: 1px solid #eee; }}
  tr:hover {{ background: #f9f9f9; }}
  .analysis-text p {{ line-height: 1.7; color: #333; }}
  .analysis-text h2 {{ font-size: 1.1rem; color: #1a1a2e; margin-top: 1.4em; }}
  .footer {{ font-size: 11px; color: #999; text-align: center; margin-top: 20px; }}
  .is-toggle {{ display:flex; gap:0; margin-bottom:14px; }}
  .is-toggle button {{ padding:6px 18px; font-size:13px; font-weight:600;
                       border:1px solid #1a1a2e; cursor:pointer; background:white;
                       color:#1a1a2e; transition:all .15s; }}
  .is-toggle button:first-child {{ border-radius:6px 0 0 6px; }}
  .is-toggle button:last-child  {{ border-radius:0 6px 6px 0; }}
  .is-toggle button.active {{ background:#1a1a2e; color:white; }}
  .is-panel {{ display:none; }}
  .is-panel.active {{ display:block; }}
  .yoy-pos {{ color:#28a745; font-weight:600; }}
  .yoy-neg {{ color:#dc3545; font-weight:600; }}
  .row-divider td {{ border-top:2px solid #dee2e6; font-weight:600;
                     background:#f8f9fa !important; color:#1a1a2e; }}
  .row-margin td {{ color:#555; font-style:italic; }}
</style>
</head>
<body>

{sankey_html}

{warning_html}

<div class="section">
  <h3>Business Model Analysis</h3>
  <div class="analysis-text">{analysis_html}</div>
</div>

{income_stmt_html}

<div class="section">
  <h3>Segment Coverage</h3>
  {coverage_html}
</div>

{sources_html}

<div class="footer">
  Generated by Financial Analysis System | Data: SEC EDGAR + Yahoo Finance |
  {agg.annual_count} annual reports, {agg.quarterly_count} quarterly reports
</div>
</body>
</html>"""

    out_path = OUTPUT_DIR / f"{agg.ticker}_sankey.html"
    out_path.write_text(full_html, encoding="utf-8")
    return out_path


def _markdown_to_html(text: str) -> str:
    try:
        import markdown
        return markdown.markdown(text, extensions=["nl2br"])
    except ImportError:
        import re
        html = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        html = re.sub(r"^## (.+)$", r"<h2>\1</h2>", html, flags=re.MULTILINE)
        html = re.sub(r"^### (.+)$", r"<h3>\1</h3>", html, flags=re.MULTILINE)
        html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)
        html = re.sub(r"\n\n+", "</p><p>", html)
        return f"<p>{html}</p>"


def _fmt_money(v):
    if v is None:
        return "—"
    a = abs(v); sign = "-" if v < 0 else ""
    if a >= 1e12: return f"{sign}${a/1e12:.2f}T"
    if a >= 1e9:  return f"{sign}${a/1e9:.2f}B"
    if a >= 1e6:  return f"{sign}${a/1e6:.1f}M"
    if a >= 1e3:  return f"{sign}${a/1e3:.0f}K"
    return f"{sign}${a:.0f}"


def _method_badge(m: str) -> str:
    colors = {
        "xbrl":      ("#28a745", "XBRL"),
        "edgar":     ("#17a2b8", "EDGAR"),
        "edgar+llm": ("#6f42c1", "EDGAR+LLM"),
        "yahoo+llm": ("#fd7e14", "Yahoo+LLM"),
        "llm":       ("#007bff", "LLM"),
    }
    bg, txt = colors.get(m or "", ("#6c757d", (m or "?").upper()))
    return (f'<span style="background:{bg};color:white;padding:1px 7px;'
            f'border-radius:8px;font-size:11px;font-weight:600">{txt}</span>')


_FINANCIAL_SECTORS_IS = {"financial", "financials", "banking", "insurance"}


def _build_income_statement_table(agg: AggregatedCompanyData) -> str:
    """Build an Income Statement section with Annual and Quarterly YoY toggle."""

    sector  = (getattr(agg, "sector", "") or "").lower()
    is_bank = sector in _FINANCIAL_SECTORS_IS

    # Detect insurance sub-type: cogs (PolicyholderBenefits) dominates revenue.
    # Use latest annual period to decide; fall back to first available period.
    _ref_sd = agg.latest_annual or (agg.annual_periods[0] if agg.annual_periods else None)
    _is_insurance = False
    if is_bank and _ref_sd and _ref_sd.total_revenue and _ref_sd.cogs:
        if _ref_sd.cogs > _ref_sd.total_revenue * INSURANCE_COGS_MIN_PCT:
            _is_insurance = True

    # ── Metrics definition ────────────────────────────────────────────────────
    if is_bank and _is_insurance:
        # Insurance P&L: large medical/claims costs flow through cogs slot.
        METRICS = [
            ("Net Revenue",              "total_revenue",    False, "divider"),
            ("Medical Costs & Claims",   "cogs",             False, "normal"),
            ("Revenue after Claims",     "gross_profit",     False, "divider"),
            ("Operating Expenses",       "sga_expense",      False, "normal"),
            ("Pre-tax Income",           "operating_income", False, "divider"),
            ("Pre-tax Margin",           None,               True,  "margin"),
            ("Income Tax",               "income_tax",       False, "normal"),
            ("Net Income",               "net_income",       False, "divider"),
            ("Net Margin",               None,               True,  "margin"),
        ]
    elif is_bank:
        # Bank P&L uses non-standard field names; SegmentData field → bank label:
        #   interest_expense → Provision for Credit Losses
        #   gross_profit     → Revenue after Provision
        #   sga_expense      → Non-Interest Expense
        #   operating_income → Pre-tax Income
        METRICS = [
            ("Net Revenue",                 "total_revenue",    False, "divider"),
            ("Provision for Credit Losses", "interest_expense", False, "normal"),
            ("Revenue after Provision",     "gross_profit",     False, "divider"),
            ("Non-Interest Expense",        "sga_expense",      False, "normal"),
            ("Pre-tax Income",              "operating_income", False, "divider"),
            ("Pre-tax Margin",              None,               True,  "margin"),
            ("Income Tax",                  "income_tax",       False, "normal"),
            ("Net Income",                  "net_income",       False, "divider"),
            ("Net Margin",                  None,               True,  "margin"),
        ]
    else:
        METRICS = [
            ("Revenue",          "total_revenue",    False, "divider"),
            ("Cost of Revenue",  "cogs",             False, "normal"),
            ("Gross Profit",     "gross_profit",     False, "divider"),
            ("Gross Margin",     None,               True,  "margin"),
            ("R&D Expense",      "rd_expense",       False, "normal"),
            ("SG&A Expense",     "sga_expense",      False, "normal"),
            ("Operating Income", "operating_income", False, "divider"),
            ("Op. Margin",       None,               True,  "margin"),
            ("Net Income",       "net_income",       False, "divider"),
            ("Net Margin",       None,               True,  "margin"),
        ]

    def _pct_margin(ni, rev):
        if ni is None or not rev:
            return None
        return ni / rev

    def _yoy_cell(curr, prev):
        if curr is None or prev is None or prev == 0:
            return '<td style="text-align:right;color:#aaa">—</td>'
        chg = (curr - prev) / abs(prev) * 100
        cls = "yoy-pos" if chg >= 0 else "yoy-neg"
        return f'<td style="text-align:right" class="{cls}">{chg:+.1f}%</td>'

    def _val_cell(v, is_pct=False):
        if v is None:
            return '<td style="text-align:right;color:#aaa">—</td>'
        if is_pct:
            return f'<td style="text-align:right">{v*100:.1f}%</td>'
        return f'<td style="text-align:right">{_fmt_money(v)}</td>'

    def _row_vals(sd):
        """Return dict of metric_name → value for a SegmentData."""
        if sd is None:
            return {}
        rev = sd.total_revenue
        if is_bank and _is_insurance:
            # Insurance: cogs = medical costs, gross_profit = revenue after claims
            claims = sd.cogs
            if claims is not None and rev and claims > rev:
                claims = None
            rac = sd.gross_profit
            if rac is None and claims is not None and rev:
                rac = rev - claims
            return {
                "Net Revenue":            sd.total_revenue,
                "Medical Costs & Claims": claims,
                "Revenue after Claims":   rac,
                "Operating Expenses":     sd.sga_expense,
                "Pre-tax Income":         sd.operating_income,
                "Pre-tax Margin":         _pct_margin(sd.operating_income, rev),
                "Income Tax":             sd.income_tax,
                "Net Income":             sd.net_income,
                "Net Margin":             _pct_margin(sd.net_income, rev),
            }
        if is_bank:
            # Sanity-check fields that are re-used for bank concepts
            provision = sd.interest_expense
            if provision is not None and rev and abs(provision) > rev * BANK_PROVISION_MAX_PCT:
                provision = None   # gross interest expense, not provision
            rap = sd.gross_profit
            if rap is not None and rev and rap > rev:
                rap = None         # not a valid revenue-after-provision
            return {
                "Net Revenue":                 sd.total_revenue,
                "Provision for Credit Losses": provision,
                "Revenue after Provision":     rap,
                "Non-Interest Expense":        sd.sga_expense,
                "Pre-tax Income":              sd.operating_income,
                "Pre-tax Margin":              _pct_margin(sd.operating_income, rev),
                "Income Tax":                  sd.income_tax,
                "Net Income":                  sd.net_income,
                "Net Margin":                  _pct_margin(sd.net_income, rev),
            }
        return {
            "Revenue":          sd.total_revenue,
            "Cost of Revenue":  sd.cogs,
            "Gross Profit":     sd.gross_profit,
            "Gross Margin":     _pct_margin(sd.gross_profit, rev),
            "R&D Expense":      sd.rd_expense,
            "SG&A Expense":     sd.sga_expense,
            "Operating Income": sd.operating_income,
            "Op. Margin":       _pct_margin(sd.operating_income, rev),
            "Net Income":       sd.net_income,
            "Net Margin":       _pct_margin(sd.net_income, rev),
        }

    def _build_table(curr_sd, prev_sd, curr_label, prev_label):
        curr_v = _row_vals(curr_sd)
        prev_v = _row_vals(prev_sd)
        rows = ""
        for label, field, is_pct, style in METRICS:
            cv = curr_v.get(label)
            pv = prev_v.get(label)
            tr_class = ""
            if style == "divider":
                tr_class = ' class="row-divider"'
            elif style == "margin":
                tr_class = ' class="row-margin"'
            rows += (
                f"<tr{tr_class}>"
                f"<td>{label}</td>"
                + _val_cell(cv, is_pct)
                + _val_cell(pv, is_pct)
                + _yoy_cell(cv, pv)
                + "</tr>"
            )
        header = (
            f"<tr><th>Metric</th>"
            f"<th style='text-align:right'>{curr_label}</th>"
            f"<th style='text-align:right'>{prev_label}</th>"
            f"<th style='text-align:right'>YoY</th></tr>"
        )
        return f"<table><thead>{header}</thead><tbody>{rows}</tbody></table>"

    # ── Annual panel ──────────────────────────────────────────────────────────
    annual = sorted(agg.annual_periods, key=lambda p: p.period, reverse=True)
    annual_html = ""
    if len(annual) >= 2:
        annual_html = _build_table(annual[0], annual[1], annual[0].period, annual[1].period)
    elif len(annual) == 1:
        annual_html = _build_table(annual[0], None, annual[0].period, "Prior Year")
    else:
        annual_html = '<p style="color:#888;font-size:13px">No annual data available.</p>'

    # ── Quarterly panel ───────────────────────────────────────────────────────
    # Build a map: "YYYYQN" → SegmentData
    qtr_map = {p.period: p for p in agg.quarterly_periods}

    # Collect paired quarters (current year Q vs prior year Q)
    qtr_pairs = []
    seen = set()
    for qp in sorted(qtr_map.keys(), reverse=True):
        parts = qp.split("Q")
        if len(parts) != 2:
            continue
        year_str, qnum = parts
        try:
            year = int(year_str)
        except ValueError:
            continue
        prior_key = f"{year - 1}Q{qnum}"
        pair_key = (qp, prior_key)
        if pair_key not in seen and prior_key in qtr_map:
            qtr_pairs.append((qtr_map[qp], qtr_map[prior_key]))
            seen.add(pair_key)

    # Limit to 4 most recent pairs
    qtr_pairs = qtr_pairs[:4]

    if qtr_pairs:
        # Build tab buttons + panels for each quarter pair
        btn_html = ""
        panels_html = ""
        for i, (curr_q, prev_q) in enumerate(qtr_pairs):
            active = "active" if i == 0 else ""
            qid = f"qtr{i}"
            label_c = curr_q.period.replace("Q", " Q")
            label_p = prev_q.period.replace("Q", " Q")
            btn_html += (
                f'<button id="btn_{qid}" class="{active}" '
                f'onclick="switchQtr(\'{qid}\')">{label_c}</button>'
            )
            tbl = _build_table(curr_q, prev_q, label_c, label_p)
            panels_html += f'<div id="panel_{qid}" class="is-panel {active}">{tbl}</div>'

        quarterly_html = f"""
<div class="is-toggle" style="margin-bottom:10px">{btn_html}</div>
{panels_html}
<script>
function switchQtr(id) {{
  document.querySelectorAll('[id^="panel_qtr"]').forEach(function(el) {{
    el.classList.remove('active');
  }});
  document.querySelectorAll('[id^="btn_qtr"]').forEach(function(el) {{
    el.classList.remove('active');
  }});
  document.getElementById('panel_' + id).classList.add('active');
  document.getElementById('btn_' + id).classList.add('active');
}}
</script>"""
    else:
        quarterly_html = '<p style="color:#888;font-size:13px">No quarterly YoY pairs available.</p>'

    # ── Combined section ──────────────────────────────────────────────────────
    return f"""<div class="section">
  <h3>Income Statement</h3>
  <div class="is-toggle">
    <button class="active" id="is-btn-annual" onclick="switchIS('annual')">Annual</button>
    <button id="is-btn-quarterly" onclick="switchIS('quarterly')">Quarterly</button>
  </div>
  <div id="is-panel-annual" class="is-panel active">{annual_html}</div>
  <div id="is-panel-quarterly" class="is-panel">{quarterly_html}</div>
  <script>
  function switchIS(mode) {{
    document.getElementById('is-panel-annual').classList.toggle('active', mode === 'annual');
    document.getElementById('is-panel-quarterly').classList.toggle('active', mode === 'quarterly');
    document.getElementById('is-btn-annual').classList.toggle('active', mode === 'annual');
    document.getElementById('is-btn-quarterly').classList.toggle('active', mode === 'quarterly');
  }}
  </script>
</div>"""


def _build_coverage_table(agg: AggregatedCompanyData) -> str:
    """Rich coverage section:

    1. Annual summary table (period | type | source | total rev | # segs | coverage %)
    2. Per-annual-period expandable block showing each segment's name / revenue / %
    3. Segment trend table (segment name × annual period) if >=2 periods of segments.
    """
    periods = sorted(agg.annual_periods + agg.quarterly_periods,
                     key=lambda s: s.period, reverse=True)

    # ── 1) Summary ----------------------------------------------------------
    summary_rows = ""
    for sd in periods:
        seg_sum = sum((s.value or 0) for s in sd.segments)
        cov_pct = min(100.0, (seg_sum / sd.total_revenue * 100) if sd.total_revenue else 0)
        cov_cell = f"{cov_pct:.0f}%" if sd.segments else "—"
        type_badge = "Annual" if sd.is_annual else "Quarterly"
        summary_rows += (
            f"<tr>"
            f"<td><strong>{sd.period}</strong></td>"
            f"<td>{type_badge}</td>"
            f"<td>{_method_badge(sd.extraction_method)}</td>"
            f"<td>{_fmt_money(sd.total_revenue)}</td>"
            f"<td>{_fmt_money(sd.net_income)}</td>"
            f"<td>{len(sd.segments)}</td>"
            f"<td>{cov_cell}</td>"
            f"<td>{sd.confidence*100:.0f}%</td>"
            f"</tr>"
        )
    summary = f"""<h4 style="margin:6px 0 8px 0;font-size:13px;color:#555">Period Summary</h4>
<table>
<thead><tr>
  <th>Period</th><th>Type</th><th>Source</th>
  <th>Revenue</th><th>Net Income</th>
  <th>#&nbsp;Segs</th><th>Segment&nbsp;Coverage</th><th>Confidence</th>
</tr></thead>
<tbody>{summary_rows}</tbody>
</table>"""

    # ── 2) Per-annual-period breakdown --------------------------------------
    detail_blocks = []
    for sd in agg.annual_periods:
        if not sd.segments:
            continue
        tot = sd.total_revenue or sum((s.value or 0) for s in sd.segments) or 0
        segs_sorted = sorted(sd.segments, key=lambda s: s.value or 0, reverse=True)
        rows = ""
        for s in segs_sorted:
            pct = (s.value / tot * 100) if (tot and s.value) else 0
            bar_w = max(1, min(100, pct))
            rows += (
                f"<tr>"
                f"<td>{s.segment_name}</td>"
                f"<td style='text-align:right'>{_fmt_money(s.value)}</td>"
                f"<td style='text-align:right'>{pct:.1f}%</td>"
                f"<td style='width:180px'>"
                f"  <div style='background:#e9ecef;border-radius:3px;height:10px;overflow:hidden'>"
                f"    <div style='background:#1f77b4;height:100%;width:{bar_w:.1f}%'></div>"
                f"  </div>"
                f"</td>"
                f"</tr>"
            )
        seg_sum = sum((s.value or 0) for s in sd.segments)
        gap = (tot - seg_sum) if tot else 0
        if gap > tot * 0.03 and tot:
            pct = gap / tot * 100
            rows += (
                f"<tr style='color:#888'>"
                f"<td><em>Other / Unallocated</em></td>"
                f"<td style='text-align:right'>{_fmt_money(gap)}</td>"
                f"<td style='text-align:right'>{pct:.1f}%</td>"
                f"<td></td></tr>"
            )
        detail_blocks.append(f"""
<details open style="margin-top:10px">
  <summary style="cursor:pointer;font-weight:600;font-size:13px;color:#1a1a2e">
    {sd.period} — {_fmt_money(sd.total_revenue)} revenue across {len(sd.segments)} segments
    &nbsp;{_method_badge(sd.extraction_method)}
  </summary>
  <table style="margin-top:6px">
  <thead><tr>
    <th>Segment</th><th style='text-align:right'>Revenue</th>
    <th style='text-align:right'>% of Total</th><th></th>
  </tr></thead>
  <tbody>{rows}</tbody>
  </table>
</details>""")

    details_html = "".join(detail_blocks)
    if not details_html:
        details_html = '<p style="color:#888;font-size:12px">No per-segment data available.</p>'

    # ── 3) Segment trend across years ---------------------------------------
    trend_html = _build_segment_trend_table(agg)

    return summary + (
        f'<h4 style="margin:18px 0 4px 0;font-size:13px;color:#555">Segment Breakdown by Period</h4>'
        + details_html
    ) + trend_html


def _build_segment_trend_table(agg: AggregatedCompanyData) -> str:
    """Build a segment × year revenue matrix from agg.segment_trend."""
    if not agg.segment_trend:
        return ""
    annual_periods = [p for p in sorted({e["period"]
                                         for segs in agg.segment_trend.values()
                                         for e in segs
                                         if e.get("is_annual")}, reverse=True)]
    if len(annual_periods) < 2:
        return ""

    # segment_name → {period: value}
    matrix = {}
    for seg_name, entries in agg.segment_trend.items():
        matrix[seg_name] = {e["period"]: e["value"]
                            for e in entries if e.get("is_annual")}

    header = "<th>Segment</th>" + "".join(
        f"<th style='text-align:right'>{p}</th>" for p in annual_periods
    ) + "<th style='text-align:right'>YoY (latest)</th>"

    rows = ""
    for seg_name in sorted(matrix, key=lambda k: -sum(v or 0 for v in matrix[k].values())):
        vals = matrix[seg_name]
        cells = "".join(
            f"<td style='text-align:right'>{_fmt_money(vals.get(p))}</td>"
            for p in annual_periods
        )
        # YoY between two most recent periods
        if len(annual_periods) >= 2:
            a, b = annual_periods[0], annual_periods[1]
            va, vb = vals.get(a), vals.get(b)
            if va is not None and vb not in (None, 0):
                yoy = (va - vb) / abs(vb) * 100
                color = "#28a745" if yoy >= 0 else "#dc3545"
                yoy_cell = f"<td style='text-align:right;color:{color};font-weight:600'>{yoy:+.1f}%</td>"
            else:
                yoy_cell = "<td style='text-align:right;color:#aaa'>—</td>"
        else:
            yoy_cell = "<td></td>"
        rows += f"<tr><td>{seg_name}</td>{cells}{yoy_cell}</tr>"

    return f"""
<h4 style="margin:20px 0 6px 0;font-size:13px;color:#555">Segment Revenue Trend (Annual)</h4>
<table>
<thead><tr>{header}</tr></thead>
<tbody>{rows}</tbody>
</table>"""


def _build_sources_section(agg: AggregatedCompanyData) -> str:
    return f"""<div class="section" style="font-size:12px;color:#666;">
  <strong>Data Sources:</strong>
  SEC EDGAR (10-K Annual Reports, 10-Q Quarterly Reports, 20-F/6-K for international filers) +
  Yahoo Finance (supplemental financial data and segment context).
  Segment data extracted via XBRL parsing and Claude AI where XBRL is incomplete.
  Coverage: {agg.annual_count} annual periods, {agg.quarterly_count} quarterly periods.
</div>"""